### ISSUE TITLE
Work Plan

### ISSUE THREAD

**Issue by davidrleonard** [davidrleonard/roadtrip#1]
## What we're working on

Roadtrip! Our prototype is aimed at adding layers of context (think datapoints, maps, targeted comments)  to photos in stories. We're in the early stages thinking about this.
## Challenge

How do we allow editors/photographers to explain deeper dimensions in their photo stories. These dimensions could include:
- Geographic data (like a map of where it was taken, or reported data related to the photo)
- Text/comments tied to a particular area of the photo
- Other related images
- Engagement opportunities (places where users can comment or share)
## Timeline

See below comment.
## Who is working on what
- @emilywithrow + @crystalgammon: Content editing, curation
- @missmagner : UI prototyping, design, usability testing
- @ashlynstill: Code/design (markup + CSS), newsy things ("I went to journalism school, I don't know")
- @davidrleonard: Code/design (interaction + JS), UX if needed
## Exit strategy

Pivot if this bombs on Thursday afternoon.

**Comment by davidrleonard** [comment]
Let's circle back on tasks for MVP:

### Big picture things:
- [ ] Finish MVP (all)
- [ ] Usability testing (@missmagner @emilywithrow)
  - [ ] Put it out in slack and see if anyone will do usability testing tomorrow during breakfast (@davidleonardii)
  - [ ] All team send out to their friends/fam/network (at your discretion) to solicit feedback all
- [ ] Multi-photo view (@ashlynstill @davidleonardii)
  - [ ] Some sort of paradigm for shifting between multiple images (@missmagner)
- [ ] Add additional interface/flow for multi-photo (@missmagner)
- [ ] Messaging for presentation (@emilywithrow)
- [ ] Create more editorial content for additional stories (@crystalgammon @emilywithrow)

### Release planning:
- [ ] v1.0: MVP
  - [ ] Users can browse the layers of **one photo**
  - [ ] Users can move between the layers easily 
  - [ ] Task: generate from mock data
  - [ ] Task: base layout, visual differentiator (accordion type view)
- [ ] v2.0: Multi-photo
  - [ ] Users can browse an article with multiple photos, and move between photos
  - [ ] Users can see graphics/images relevant to a specific layer
  - [ ] Task: refined design in prototype
- [ ] v3.0: Create your own!
  - [ ] User can create a layered photo story from a publication's story page
  - [ ] User can share out a link to the layered story
  - [ ] Task: api scrapes specific news sites
  - [ ] Task: mobile/tablet interaction design
- [ ] v4.0: AFTER DEMO, FUTURE: Cool stuff
  - [ ] User can create layered photo from many different publication pages
  - [ ] User can share specific context/layers on social media in an easy, engaging way

### Publications we could possibly launch with:
- Three various ones in tone: roundup, funny, serious
- BuzzFeed
- Washington Post
- AJC
- Yale360
- New York Times
